'use client';
import Link from 'next/link';
import {RecordEditor} from '@/components/record-editor';
import {AttendanceResetDialog,resetLabels,type ResetScope} from '@/components/attendance-reset-dialog';
import { cloneElement, isValidElement, useId, useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode, type ReactElement } from 'react';
type Employee={id:string;name:string;username:string;hireDate:string;payType:'hourly'|'monthly';active:boolean};
type RecordRow={id:string;employeeId:string;clockIn:string;clockOut:string|null;deductionMinutes:number;credited:boolean;reason:string;confirmed:boolean;workDate:string;calculatedMinutes:number|null;calculationError?:string|null};
type Wage={id:string;employeeId:string;amount:number;effectiveDate:string};
type Period={id:string;employeeId:string;startDay:number;effectiveDate:string};
type Pay={employeeId:string;periodStart:string;periodEnd:string;days:number;minutes:number;amount:number|null;unconfirmed:number;incomplete:number;excluded:number;rates:number[]};
type State={user:{id:string;role:string;name?:string;employeeId?:string;username:string};employees:Employee[];attendance:RecordRow[];wageHistory:Wage[];periodHistory:Period[];audits:{id:string;reason:string;createdAt?:string;at?:string;actorName?:string;before?:unknown;after?:unknown}[];payroll?:Pay[];demo?:boolean};
type Modal={kind:'record'|'employee'|'wage'|'period'|'password'|'history'|'reset';resetScope?:ResetScope;record?:RecordRow;employee?:Employee}|null;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const time=(v?:string|null)=>v?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)):'—';
const money=(v:number)=>new Intl.NumberFormat('ko-KR').format(v);
const duration=(v:number|null|undefined)=>v==null?'계산 미완료':`${Math.floor(Math.round(v)/60)}시간 ${Math.round(v)%60}분`;
const localInput=(v?:string|null)=>v?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(v)).replace(' ','T'):'';
function Icon({name,size=20}:{name:string;size?:number}) { const paths:Record<string,ReactNode>={today:<><rect x="4" y="5" width="16" height="16" rx="4"/><path d="M8 3v4m8-4v4M4 11h16m-12 5h3"/></>,attendance:<><rect x="5" y="3" width="14" height="18" rx="3"/><path d="m8 9 1 1 2-2m2 1h3m-8 6 1 1 2-2m2 1h3"/></>,employees:<><circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 4v2"/></>,payroll:<><rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 9h18m-5 5h5M7 3v4"/></>,arrow:<path d="m9 5 7 7-7 7"/>,plus:<path d="M12 5v14M5 12h14"/>,check:<path d="m5 12 4 4L19 6"/>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,logout:<><path d="M9 4H5v16h4m6-12 4 4-4 4m-6-4h10"/></>,close:<path d="m6 6 12 12M6 18 18 6"/>,edit:<><path d="m15 4 5 5-11 11H4v-5L15 4Z"/><path d="m12 7 5 5"/></>,info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-11v1"/></>,sun:<><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/></>,search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></>};return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round">{paths[name]||paths.info}</svg> }
function Badge({children,tone='gray'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}><span className="status-dot"/>{children}</span>}
function Field({label,children}:{label:string;children:ReactNode}){const id=useId();return <label className="field"><span id={id}>{label}</span>{isValidElement(children)?cloneElement(children as ReactElement<{"aria-labelledby"?:string}>,{"aria-labelledby":id}):children}</label>}
function AuditValues({value}:{value:unknown}){if(!value||typeof value!=='object')return <p>기록 없음</p>;const labels:Record<string,string>={clockIn:'출근',clockOut:'퇴근',deductionMinutes:'차감시간',credited:'1시간 인정',reason:'사유',confirmed:'확인 완료',workDate:'근무일',amount:'시급',effectiveDate:'적용일',startDay:'매월 시작일',name:'이름',username:'아이디',hireDate:'입사일',payType:'급여 형태',active:'재직 상태'};return <dl>{Object.entries(value).filter(([key])=>labels[key]).map(([key,v])=><div key={key}><dt>{labels[key]}</dt><dd>{key==='clockIn'||key==='clockOut'?v?`${localInput(String(v)).replace('T',' ')}`:'미퇴근':typeof v==='boolean'?v?'예':'아니요':key==='deductionMinutes'?`${v}분`:key==='amount'?`${money(Number(v))}원`:key==='payType'?v==='hourly'?'시급제':'월급제':String(v??'—')}</dd></div>)}</dl>}
export default function Home(){
 const [state,setState]=useState<State|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[tab,setTab]=useState('today'),[modal,setModal]=useState<Modal>(null),[selected,setSelected]=useState(''),[date,setDate]=useState(''),[search,setSearch]=useState(''),[payDate,setPayDate]=useState(today()),[sampleLogin,setSampleLogin]=useState(false),[pendingMutation,setPendingMutation]=useState<{endpoint:string;body:unknown;message:string}|null>(null);
 const clockRequests=useRef<Partial<Record<'in'|'out',string>>>({});const clockBusy=useRef(false);
 const owner=state?.user.role==='owner'; const employees=state?.employees||[]; const rows=state?.attendance||[]; const name=(id:string)=>employees.find(e=>e.id===id)?.name||'직원';
 const load=useCallback(async (lookupDate=payDate)=>{setLoading(true);try{const r=await fetch(`/api/state?date=${encodeURIComponent(lookupDate)}`,{cache:'no-store'});if(r.status===401){setState(null);setError('');return true}const d=await r.json();if(!r.ok)throw Error(d.error||'데이터를 불러오지 못했습니다.');setState(d);setError('');return true}catch(e){setError(e instanceof TypeError?'통신에 실패했습니다. 연결을 확인하고 다시 시도해 주세요.':e instanceof Error?e.message:'연결을 확인해 주세요.');return false}finally{setLoading(false)}},[payDate]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{setError('');setPendingMutation(null)},[tab,modal]);
 useEffect(()=>{void fetch('/api/config').then(r=>r.ok?r.json():null).then(d=>setSampleLogin(Boolean(d?.sampleLogin))).catch(()=>{});if('serviceWorker'in navigator)void navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement as HTMLElement;const dialog=document.querySelector<HTMLElement>('[role=dialog]');const focusables=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not([type=hidden]):not(:disabled),select:not(:disabled),textarea:not(:disabled),summary')||[]);(focusables()[0]??dialog)?.focus();const h=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)setModal(null);if(e.key==='Tab'){const list=focusables();const first=list[0],last=list.at(-1);if(!first){e.preventDefault();dialog?.focus();return}if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};const old=document.body.style.overflow;document.body.style.overflow='hidden';window.addEventListener('keydown',h);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',h);previous?.focus()}},[modal,busy]);
 async function mutate(endpoint:string,body:unknown,message='저장했습니다.'){
  setBusy(true);setError('');setToast('');setPendingMutation(null);
  try{
   const r=await fetch(`/api/${endpoint}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
   const d=await r.json();if(!r.ok)throw Error(d.error||'요청을 처리하지 못했습니다.');
   setPendingMutation(null);setModal(null);
   if(endpoint==='clock'){const action=(body as {action:'in'|'out'}).action;delete clockRequests.current[action]}
   if(endpoint==='login'||endpoint==='logout'||endpoint==='password'){setTab('today');setSelected('');setDate('');setSearch('');setPayDate(today());clockRequests.current={}}
   if(endpoint==='logout'||endpoint==='password'){setState(null);setToast(endpoint==='password'?'비밀번호를 변경했습니다. 다시 로그인해 주세요.':message);return true}
   const refreshed=await load(endpoint==='login'?today():payDate);
   if(refreshed)setToast(message);else setError(endpoint==='login'?'로그인됐지만 최신 기록을 불러오지 못했습니다. 다시 불러오기를 눌러 주세요.':'저장됐지만 최신 기록을 불러오지 못했습니다. 다시 불러오기를 눌러 주세요.');
   return true;
  }catch(e){setPendingMutation({endpoint,body,message});setError(e instanceof TypeError?'통신에 실패했습니다. 연결을 확인하고 다시 시도해 주세요.':e instanceof Error?e.message:'통신 오류로 저장 여부를 확인하지 못했습니다. 다시 시도해 주세요.');return false}finally{setBusy(false)}
 }
 function retryAction(){return pendingMutation?mutate(pendingMutation.endpoint,pendingMutation.body,pendingMutation.message):load()}

 async function recordClock(action:'in'|'out'){if(clockBusy.current)return;clockBusy.current=true;const requestId=clockRequests.current[action]??crypto.randomUUID();clockRequests.current[action]=requestId;try{if(await mutate('clock',{action,requestId},action==='in'?'출근을 기록했습니다.':'퇴근을 기록했습니다.'))delete clockRequests.current[action]}finally{clockBusy.current=false}}
 const nav=owner?[['today','오늘'],['attendance','출석부'],['employees','직원'],['payroll','급여']]:[['today','오늘'],['attendance','내 출석부'],['profile','내 정보']];
 const active=employees.filter(e=>e.active);const todayRows=rows.filter(r=>r.workDate===today());const working=rows.filter(r=>!r.clockOut);const pending=rows.filter(r=>!r.confirmed);const currentEmployee=employees.find(e=>e.id===state?.user.employeeId)||employees[0];const isWorking=working.some(r=>r.employeeId===currentEmployee?.id);const completedToday=todayRows.some(r=>r.employeeId===currentEmployee?.id&&Boolean(r.clockOut));
 function recordCard(r:RecordRow){return <article className="record-card" key={r.id}><div className="record-top"><div className="person"><div className="avatar">{name(r.employeeId).slice(-2)}</div><div><strong>{name(r.employeeId)}</strong><span>{r.workDate} · {employees.find(e=>e.id===r.employeeId)?.payType==='monthly'?'월급제':'시급제'}</span></div></div><Badge tone={!r.clockOut?'orange':r.confirmed?'green':'gray'}>{!r.clockOut?'근무 중':r.confirmed?'확인 완료':'확인 전'}</Badge></div><div className="time-grid"><div><span>출근</span><b>{time(r.clockIn)}</b></div><div><span>퇴근</span><b>{time(r.clockOut)}{r.clockOut&&localInput(r.clockOut).slice(0,10)>r.workDate&&<small> +1일</small>}</b></div><div><span>계산시간</span><b className="green-text">{r.calculationError?'계산 보정 필요':duration(r.calculatedMinutes)}</b></div></div><div className="record-detail"><span>차감 {duration(r.deductionMinutes)}</span><span>인정 {r.credited?'1시간':'없음'}</span></div>{r.reason&&<p className="reason">{r.reason}</p>}{r.calculationError&&<p className="inline-warning"><Icon name="info" size={16}/>차감시간 확인 필요 · 급여 합계에서 제외</p>}{owner&&<div className="record-actions"><button onClick={()=>setModal({kind:'record',record:r})}><Icon name="edit" size={16}/>기록 수정</button><button disabled={busy} className={r.credited?'selected':''} onClick={()=>mutate('attendance',{...r,credited:!r.credited,confirmed:false,reason:r.credited?'근무 1시간 인정 취소':'브레이크타임 근무 1시간 인정'},r.credited?'근무 인정을 취소했습니다.':'근무 1시간을 인정했습니다.')}><Icon name="plus" size={16}/>{r.credited?'1시간 인정 취소':'근무 1시간 인정'}</button>{!r.confirmed&&r.clockOut&&!r.calculationError&&<button disabled={busy} className="confirm" onClick={()=>mutate('attendance',{...r,confirmed:true,reason:r.reason||'근무기록 확인'},'확인 완료했습니다.')}><Icon name="check" size={16}/>확인</button>}</div>}</article>}
 async function submitModal(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),v=Object.fromEntries(f.entries());if(modal?.kind==='record')await mutate('attendance',{id:modal.record?.id,employeeId:v.employeeId,clockIn:new Date(`${v.clockIn}+09:00`).toISOString(),clockOut:v.clockOut?new Date(`${v.clockOut}+09:00`).toISOString():null,deductionMinutes:Number(v.deductionMinutes),credited:f.get('credited')==='on',reason:v.reason,confirmed:false});if(modal?.kind==='employee')await mutate('employees',{id:modal.employee?.id,...v,active:f.get('active')==='on'});if(modal?.kind==='wage')await mutate('wages',{...v,employeeId:modal.employee?.id,amount:Number(v.amount)});if(modal?.kind==='period')await mutate('periods',{...v,employeeId:modal.employee?.id,startDay:Number(v.startDay)});if(modal?.kind==='password')await mutate('password',v,'비밀번호를 변경했습니다.');}
 if(loading&&!state)return <div className="loading-screen"><div className="brand-mark"><Icon name="check" size={30}/></div><h2>오늘근무</h2><p>불러오는 중…</p><span className="loader"/></div>;
 if(!state)return <main className="login-page"><section className="login-panel"><div className="login-form"><div className="brand"><div className="brand-mark"><Icon name="check" size={26}/></div>오늘근무</div><h1>로그인</h1><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate('login',Object.fromEntries(f),'로그인했습니다.')}}><Field label="아이디"><input name="username" autoComplete="username" placeholder="아이디를 입력해 주세요" required/></Field><Field label="비밀번호"><input name="password" type="password" autoComplete="current-password" placeholder="비밀번호를 입력해 주세요" required/></Field>{toast&&<p role="status" className="bottom-note">{toast}</p>}{error&&<div role="alert" className="error">{error}<button type="button" disabled={busy} onClick={()=>void retryAction()}>{pendingMutation?'요청 다시 시도':'다시 불러오기'}</button></div>}<button disabled={busy} className="primary full">{busy?'로그인 중…':'로그인'}<Icon name="arrow" size={18}/></button></form>{sampleLogin&&<div className="demo-box"><b>샘플 매장 둘러보기</b><div><button disabled={busy} onClick={()=>mutate('login',{username:'owner',password:'demo1234'},'사장님 데모에 입장했습니다.')}>사장님으로 체험 <Icon name="arrow" size={15}/></button><button disabled={busy} onClick={()=>mutate('login',{username:'employee',password:'demo1234'},'직원 데모에 입장했습니다.')}>직원으로 체험 <Icon name="arrow" size={15}/></button></div></div>}<p className="login-help"><Icon name="info" size={15}/> 계정 문의 · 사장님</p></div></section></main>;
 return <div className="app-shell"><aside className="sidebar"><Link className="brand" href="/"><div className="brand-mark"><Icon name="check" size={26}/></div>오늘근무<span className="brand-dot"/></Link><div className="store-label"><span className="store-icon">온</span><div><b>온기 식당</b></div></div><nav>{nav.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setError('')}}><Icon name={key==='profile'?'employees':key}/><span>{label}</span>{key==='attendance'&&pending.length>0&&<small>{pending.length}</small>}</button>)}</nav><div className="sidebar-bottom"><button className="account" onClick={()=>setModal({kind:'password'})}><div className="avatar dark">{owner?'사':'나'}</div><div><b>{owner?'사장님':currentEmployee?.name||'직원'}</b><span>{owner?'매장 관리자':'직원 계정'}</span></div><Icon name="edit" size={16}/></button></div></aside><div className="workspace"><header className="topbar"><div className="breadcrumb">온기 식당 <span>/</span> <b>{nav.find(x=>x[0]===tab)?.[1]}</b></div><div className="top-actions"><span className="demo-pill">{state.demo?'샘플 매장':'매장 운영'}</span><span className="date-label">{today().replaceAll('-','. ')}</span><button aria-label="로그아웃" title="로그아웃" onClick={()=>mutate('logout',{},'로그아웃했습니다.')}><Icon name="logout"/></button></div></header><main className="content">{error&&<div className="error global-error" role="alert"><Icon name="info"/>{error}<button disabled={busy} onClick={()=>void retryAction()}>{pendingMutation?'요청 다시 시도':'다시 불러오기'}</button></div>}
 {tab==='today'&&<><div className="page-heading"><div><div className="eyebrow">{new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'long'}).format(new Date())}</div><h1>{owner?'오늘 근무':'출퇴근'}</h1></div>{owner&&<button className="primary" onClick={()=>setModal({kind:'record'})}><Icon name="plus" size={18}/>근무기록 추가</button>}</div>
 {!owner&&<section className="hero clock-panel"><div className="clock-status"><span className="hero-tag">{currentEmployee?.name} · 오늘 근무</span><h2>{isWorking?'근무 중':completedToday?'퇴근 완료':'출근 전'}</h2>{isWorking&&<p>출근 {time(working.find(r=>r.employeeId===currentEmployee?.id)?.clockIn)}</p>}</div><div className="clock-buttons"><button className="light-button" disabled={busy||loading} aria-busy={busy} onClick={()=>recordClock(isWorking?'out':'in')}><Icon name={isWorking?'logout':'sun'}/>{busy?'기록 중…':isWorking?'퇴근하기':completedToday?'다시 출근하기':'출근하기'}</button></div></section>}
 {owner&&<><section className="stats"><div className="stat"><div className="stat-label">오늘 출근<Icon name="employees"/></div><p>{new Set(todayRows.map(r=>r.employeeId)).size}<span> / {active.length}명</span></p></div><div className="stat"><div className="stat-label">근무 중<Icon name="clock"/></div><p>{working.length}<span>명</span></p></div><button className="stat attention" onClick={()=>setTab('attendance')}><div className="stat-label">확인 필요<Icon name="attendance"/></div><p>{pending.length}<span>건</span></p></button></section><section className="section"><div className="section-heading"><h2>오늘의 직원 <span>{active.length}</span></h2><button className="text-button" onClick={()=>setTab('attendance')}>출석부 전체보기 <Icon name="arrow" size={16}/></button></div><div className="team-list"><div className="team-table-head"><span>직원</span><span>근무 상태</span><span>출근</span><span>퇴근</span><span>계산시간</span><span/></div>{active.map(e=>{const r=working.find(r=>r.employeeId===e.id)||todayRows.find(r=>r.employeeId===e.id);return <div className="team-row" key={e.id}><div className="person"><div className="avatar">{e.name.slice(-2)}</div><div><strong>{e.name}</strong><span>{e.payType==='hourly'?'시급제':'월급제'}</span></div></div><Badge tone={r?!r.clockOut?'green':'gray':'orange'}>{r?!r.clockOut?'근무 중':'퇴근 완료':'출근 전'}</Badge><div className="table-time"><span>출근 </span>{time(r?.clockIn)}</div><div className="table-time"><span>퇴근 </span>{time(r?.clockOut)}</div><div className="table-duration"><span>계산시간</span>{r?r.calculationError?'계산 보정 필요':duration(r.calculatedMinutes):'—'}</div><button aria-label={`${e.name} 근무기록 ${r?'수정':'추가'}`} onClick={()=>setModal({kind:'record',record:r,employee:e})}><Icon name="arrow" size={18}/></button></div>})}{!active.length&&<div className="empty">등록된 직원이 없습니다.</div>}</div></section><div className="bottom-note"><Icon name="info" size={17}/><span>미퇴근 기록은 급여 합계에서 제외됩니다.</span></div></>}{!owner&&<section className="section"><div className="section-heading"><h2>오늘의 기록</h2><button className="text-button" onClick={()=>setTab('attendance')}>내 출석부 <Icon name="arrow" size={16}/></button></div>{rows.some(r=>r.workDate===today()||!r.clockOut||localInput(r.clockOut).slice(0,10)===today())?rows.filter(r=>r.workDate===today()||!r.clockOut||localInput(r.clockOut).slice(0,10)===today()).map(recordCard):<div className="empty"><Icon name="sun" size={30}/><h3>오늘 출근 기록이 없습니다</h3></div>}</section>}</>}
 {tab==='attendance'&&<><div className="page-heading"><div><h1>{owner?'출석부':'내 출석부'}</h1></div><div className="heading-actions"><button className="secondary" onClick={()=>setModal({kind:'history'})}>조정 내역</button>{owner&&<button className="primary" onClick={()=>setModal({kind:'record'})}><Icon name="plus" size={18}/>기록 추가</button>}</div></div>{owner&&<div className="attendance-reset-bar"><div><b>출석부 초기화</b><span>전체 직원 · 삭제 전 대상 확인</span></div><div className="reset-options">{(['today','week','month'] as ResetScope[]).map(scope=><button key={scope} className="reset-option" disabled={busy||loading} onClick={()=>setModal({kind:'reset',resetScope:scope})}>{resetLabels[scope]} 초기화</button>)}</div></div>}<div className="filters">{owner&&<Field label="직원"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">전체 직원</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></Field>}<Field label="근무일"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><button className="text-button" onClick={()=>{setDate('');setSelected('')}}>필터 초기화</button><span className="filter-count">총 {rows.filter(r=>(!selected||r.employeeId===selected)&&(!date||r.workDate===date)).length}건</span></div><div className="record-grid">{rows.filter(r=>(!selected||r.employeeId===selected)&&(!date||r.workDate===date)).sort((a,b)=>b.clockIn.localeCompare(a.clockIn)).map(recordCard)}</div>{!rows.filter(r=>(!selected||r.employeeId===selected)&&(!date||r.workDate===date)).length&&<div className="empty"><Icon name="attendance" size={30}/><h3>근무기록이 없습니다</h3><p>조회 조건을 변경해 주세요.</p></div>}</>}
 {tab==='employees'&&owner&&<><div className="page-heading"><div><h1>직원 <span className="count">{active.length}</span></h1></div><button className="primary" onClick={()=>setModal({kind:'employee'})}><Icon name="plus" size={18}/>직원 등록</button></div><div className="search-box"><Icon name="search"/><input aria-label="직원 이름 검색" placeholder="직원 이름으로 검색" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="employee-grid">{employees.filter(e=>e.name.includes(search)).map(e=>{const wages=(state.wageHistory||[]).filter(w=>w.employeeId===e.id).sort((a,b)=>b.effectiveDate.localeCompare(a.effectiveDate));const w=wages.find(w=>w.effectiveDate<=today());const periods=(state.periodHistory||[]).filter(p=>p.employeeId===e.id).sort((a,b)=>b.effectiveDate.localeCompare(a.effectiveDate));const p=periods.find(p=>p.effectiveDate<=today());return <article className="employee-card" key={e.id}><div className="record-top"><div className="person"><div className="avatar large">{e.name.slice(-2)}</div><div><strong>{e.name}</strong><span>@{e.username}</span></div></div><Badge tone={e.active?'green':'gray'}>{e.active?'재직 중':'퇴사'}</Badge></div><dl><div><dt>입사일</dt><dd>{e.hireDate}</dd></div><div><dt>급여 형태</dt><dd>{e.payType==='hourly'?'시급제':'월급제'}</dd></div><div><dt>현재 시급</dt><dd>{e.payType==='hourly'?`${money(w?.amount||0)}원`:'시간별 계산 없음'}</dd></div><div><dt>산정기간</dt><dd>매월 {p?.startDay||1}일 시작</dd></div></dl><div className="employee-actions"><button onClick={()=>setModal({kind:'employee',employee:e})}>계정 · 정보 수정</button><button onClick={()=>setModal({kind:'wage',employee:e})}>시급 이력</button><button onClick={()=>setModal({kind:'period',employee:e})}>산정기간</button></div></article>})}</div>{!employees.filter(e=>e.name.includes(search)).length&&<div className="empty">{search?'검색 결과가 없습니다.':'등록된 직원이 없습니다.'}</div>}</>}
 {tab==='payroll'&&owner&&<><div className="page-heading"><div><h1>급여 정산</h1></div></div><div className="filters"><Field label="산정기간 조회 기준일"><input type="date" value={payDate} onChange={e=>{if(e.target.value)setPayDate(e.target.value)}}/></Field><span className="filter-count">{loading?'집계 중…':'직원별 산정기간 적용'}</span></div><div className="payroll-summary"><div><span>선택 산정기간 예상 급여 합계</span><h2>{money((state.payroll||[]).reduce((s,p)=>s+(p.amount??0),0))}<small>원</small></h2></div><Icon name="payroll" size={42}/></div><div className="bottom-note"><Icon name="info" size={18}/><span>수당·세금·보험료 미포함. 미완료·오류 기록 제외. 월급제는 근태만 집계합니다.</span></div><div className="record-grid">{(state.payroll||[]).map(p=><article key={p.employeeId} className="employee-card"><div className="record-top"><div className="person"><div className="avatar">{name(p.employeeId).slice(-2)}</div><div><strong>{name(p.employeeId)}</strong><span>{p.periodStart} ~ {p.periodEnd}</span></div></div><Badge>{employees.find(e=>e.id===p.employeeId)?.payType==='monthly'?'월급제':'시급제'}</Badge></div><div className="pay-amount">{employees.find(e=>e.id===p.employeeId)?.payType==='monthly'?'근태 집계':`${money(p.amount??0)}원`}</div><dl><div><dt>출근일수 / 계산시간</dt><dd>{p.days}일 / {duration(p.minutes)}</dd></div><div><dt>적용 시급</dt><dd>{p.rates.length?p.rates.map(n=>`${money(n)}원`).join(' · '):'해당 없음'}</dd></div><div><dt>미확인 / 미완료</dt><dd>{p.unconfirmed}건 / {p.incomplete}건</dd></div><div><dt>급여 합계 제외</dt><dd className={p.excluded?'orange-text':''}>{p.excluded}건</dd></div></dl></article>)}</div>{!state.payroll?.length&&<div className="empty">급여 집계가 없습니다.</div>}</>}
 {tab==='profile'&&!owner&&<><div className="page-heading"><div><h1>내 정보</h1></div></div><article className="profile-card"><div className="person"><div className="avatar large">{currentEmployee?.name.slice(-2)}</div><div><h2>{currentEmployee?.name}</h2><span>@{state.user.username}</span></div></div><dl><div><dt>입사일</dt><dd>{currentEmployee?.hireDate}</dd></div><div><dt>급여 형태</dt><dd>{currentEmployee?.payType==='monthly'?'월급제':'시급제'}</dd></div><div><dt>현재 시급</dt><dd>{currentEmployee?.payType==='monthly'?'해당 없음':`${money([...state.wageHistory].sort((a,b)=>b.effectiveDate.localeCompare(a.effectiveDate)).find(w=>w.effectiveDate<=today())?.amount||0)}원`}</dd></div></dl><h3>시급 변경 이력</h3>{state.wageHistory.map(w=><div className="history-row" key={w.id}><span>{w.effectiveDate}부터</span><b>{money(w.amount)}원</b></div>)}<h3>급여 산정기간 이력</h3>{state.periodHistory.map(p=><div className="history-row" key={p.id}><span>{p.effectiveDate}부터</span><b>매월 {p.startDay}일 시작</b></div>)}<button className="secondary full" onClick={()=>setModal({kind:'password'})}>비밀번호 변경</button></article></>}
 </main></div><nav className="mobile-nav">{nav.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon name={key==='profile'?'employees':key}/>{label}</button>)}</nav>{toast&&<div role="status" className="toast"><Icon name="check" size={19}/>{toast}</div>}
 {modal?.kind==='reset'&&<AttendanceResetDialog scope={modal.resetScope!} busy={busy} onBusy={setBusy} onClose={()=>setModal(null)} onComplete={count=>{setModal(null);void load().then(ok=>{if(ok)setToast(`${count}건의 출석 기록을 초기화했습니다.`);else setError('초기화됐지만 최신 기록을 불러오지 못했습니다. 다시 불러오기를 눌러 주세요.')})}}/>}
 {modal&&modal.kind!=='reset'&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setModal(null)}}><section className="modal" role="dialog" tabIndex={-1} aria-modal="true" aria-labelledby="modal-title"><header><div><span className="eyebrow">{modal.record?name(modal.record.employeeId):modal.employee?.name||'오늘근무'}</span><h2 id="modal-title">{{record:modal.record?'근무기록 수정':'근무기록 추가',employee:modal.employee?'직원 · 계정 관리':'새 직원 등록',wage:'시급 변경 이력',period:'급여 산정기간',password:'비밀번호 변경',history:'근무 조정 내역'}[modal.kind]}</h2></div><button aria-label="닫기" disabled={busy} onClick={()=>setModal(null)}><Icon name="close"/></button></header><form onSubmit={submitModal}><div className="modal-body">{error&&<div className="error" role="alert">{error}<button type="button" disabled={busy} onClick={()=>void retryAction()}>{pendingMutation?'요청 다시 시도':'다시 불러오기'}</button></div>}
 {modal.kind==='record'&&<RecordEditor record={modal.record} employeeId={modal.employee?.id||selected} employees={employees} busy={busy}/>}
 {modal.kind==='employee'&&<><div className="form-grid"><Field label="직원 이름"><input name="name" defaultValue={modal.employee?.name} required/></Field><Field label="입사일"><input name="hireDate" type="date" defaultValue={modal.employee?.hireDate||today()} required/></Field></div><Field label="로그인 아이디"><input name="username" autoComplete="off" defaultValue={modal.employee?.username} required/></Field><Field label={modal.employee?'새 비밀번호 (변경할 때만 입력)':'임시 비밀번호 (8자 이상)'}><input name="password" type="password" minLength={8} autoComplete="new-password" required={!modal.employee}/></Field><Field label="급여 형태"><select name="payType" defaultValue={modal.employee?.payType||'hourly'}><option value="hourly">시급제</option><option value="monthly">월급제 · 근태만 집계</option></select></Field><label className="checkbox-field"><input name="active" type="checkbox" defaultChecked={modal.employee?.active??true}/><div><b>재직 중 · 로그인 허용</b><span>해제 시 로그인 차단 · 기존 기록 유지</span></div></label><p className="field-help">시급·산정기간은 등록 후 설정</p></>}
 {modal.kind==='wage'&&<><div className="history-list">{state.wageHistory.filter(w=>w.employeeId===modal.employee?.id).map(w=><div className="history-row" key={w.id}><span>{w.effectiveDate}부터</span><b>{money(w.amount)}원</b></div>)}</div><Field label="새 시급 (원)"><input type="number" name="amount" inputMode="numeric" min="1" step="1" required/></Field><Field label="적용 시작일"><input type="date" name="effectiveDate" defaultValue={today()} required/></Field><p className="field-help">적용일 이전 근무는 기존 시급 유지</p></>}
 {modal.kind==='period'&&<><div className="history-list">{state.periodHistory.filter(p=>p.employeeId===modal.employee?.id).map(p=><div className="history-row" key={p.id}><span>{p.effectiveDate}부터</span><b>매월 {p.startDay}일 시작</b></div>)}</div><Field label="매월 산정 시작일"><input name="startDay" type="number" min="1" max="31" defaultValue="1" inputMode="numeric" required/></Field><Field label="적용 시작 기간의 첫날"><input type="date" name="effectiveDate" required/></Field><p className="field-help">매월 21일 시작 시 다음 달 20일까지. 없는 날짜는 월말로 적용합니다. 적용 시작일은 기존 기간의 경계일이어야 합니다.</p></>}
 {modal.kind==='password'&&<><Field label="현재 비밀번호"><input name="currentPassword" type="password" autoComplete="current-password" required/></Field><Field label="새 비밀번호 (8자 이상)"><input name="newPassword" type="password" autoComplete="new-password" minLength={8} required/></Field></>}
 {modal.kind==='history'&&<div className="audit-list">{state.audits.length?state.audits.map(a=><article key={a.id}><b>{a.reason||'근무기록 변경'}</b><p>{a.actorName||'관리자'} · {a.createdAt||a.at?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'medium',timeStyle:'short'}).format(new Date(a.createdAt||a.at!)):''}</p><details><summary>변경 전후 보기</summary><div className="audit-values"><b>변경 전</b><AuditValues value={a.before}/><b>변경 후</b><AuditValues value={a.after}/></div></details></article>):<div className="empty">아직 조정 내역이 없어요.</div>}</div>}</div>{modal.kind!=='history'&&<div className="modal-footer"><button type="button" className="secondary" disabled={busy} onClick={()=>setModal(null)}>취소</button><button className="primary" disabled={busy}>{busy?'저장 중…':'저장하기'}<Icon name="check" size={18}/></button></div>}</form></section></div>}</div>;
}
