import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
const origin=process.env.TEST_ORIGIN||'http://localhost:3000';
async function call(path,body,cookie='',expected=200){const r=await fetch(origin+'/api/'+path,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return {data,cookie:r.headers.get('set-cookie')?.split(';')[0]||cookie};}
const owner=await call('login',{username:'owner',password:'demo1234'});
const id='verify'+Date.now();
const emp=(await call('employees',{name:'기능검증 직원',username:id,password:'testpass123',hireDate:'2026-01-01',payType:'hourly',active:true},owner.cookie)).data.employee;
await call('wages',{employeeId:emp.id,amount:12000,effectiveDate:'2026-01-01'},owner.cookie);
const worker=await call('login',{username:id,password:'testpass123'});
await call('state',null,'',401);
let s=(await call('state?employeeId=other',null,worker.cookie)).data;
assert(!('payroll'in s));assert(s.employees.every(e=>e.id===emp.id));assert(s.attendance.every(e=>e.employeeId===emp.id));
for(const path of ['wages','employees','attendance','periods','payroll']) await call(path,{},worker.cookie,403);
const key=randomUUID();await Promise.all([call('clock',{action:'in',requestId:key},worker.cookie),call('clock',{action:'in',requestId:key},worker.cookie)]);
await call('clock',{action:'in',requestId:randomUUID()},worker.cookie,409);
const outkey=randomUUID();await call('clock',{action:'out',requestId:outkey},worker.cookie);await call('clock',{action:'out',requestId:outkey},worker.cookie);
s=(await call('state',null,worker.cookie)).data;assert.equal(s.attendance.length,1);assert(s.attendance[0].clockOut);assert(s.attendance[0].calculationError);
let rec=s.attendance[0];const date=new Date(Date.parse(rec.workDate)-86400000).toISOString().slice(0,10);
await call('attendance',{...rec,clockIn:date+'T01:00:00.000Z',clockOut:date+'T13:00:00.000Z',deductionMinutes:120,credited:false,reason:'12시간 검증'},owner.cookie);
rec=(await call('state',null,worker.cookie)).data.attendance[0];assert.equal(rec.calculatedMinutes,600);
await call('attendance',{...rec,confirmed:true},owner.cookie);
await call('attendance',{...rec,credited:true,reason:'브레이크타임 응대'},owner.cookie);
await call('attendance',{...rec,credited:true,reason:'브레이크타임 응대'},owner.cookie);
rec=(await call('state',null,worker.cookie)).data.attendance[0];assert.equal(rec.calculatedMinutes,660);assert.equal(rec.confirmed,false);
await call('attendance',{...rec,deductionMinutes:240,credited:false,reason:'분할근무 공백'},owner.cookie);
s=(await call('state',null,worker.cookie)).data;assert.equal(s.attendance[0].calculatedMinutes,480);assert(s.audits.length>=4);assert(!JSON.stringify(s).includes('passwordHash'));
const payroll=(await call('state',null,owner.cookie)).data.payroll.find(p=>p.employeeId===emp.id);assert.equal(payroll.amount,96000);
// A completed shift must not prevent another shift on the same day.
await call('clock',{action:'in',requestId:randomUUID()},worker.cookie);
const firstToday=(await call('clock',{action:'out',requestId:randomUUID()},worker.cookie)).data.attendance;
const nextKey=randomUUID();
await Promise.all([call('clock',{action:'in',requestId:nextKey},worker.cookie),call('clock',{action:'in',requestId:nextKey},worker.cookie)]);
await call('clock',{action:'in',requestId:randomUUID()},worker.cookie,409);
const secondToday=(await call('clock',{action:'out',requestId:randomUUID()},worker.cookie)).data.attendance;
assert.notEqual(firstToday.id,secondToday.id);assert.equal(firstToday.workDate,secondToday.workDate);
s=(await call('state',null,worker.cookie)).data;
assert.equal(s.attendance.length,3);assert(s.attendance.every(a=>a.clockOut));
const csrf=await fetch(origin+'/api/clock',{method:'POST',headers:{Origin:'https://invalid.test','Content-Type':'application/json',Cookie:worker.cookie},body:JSON.stringify({action:'in',requestId:randomUUID()})});assert.equal(csrf.status,403);
await call('employees',{...emp,password:'',active:false},owner.cookie);
await call('state',null,worker.cookie,401);await call('login',{username:id,password:'testpass123'},'',403);
assert((await call('state',null,owner.cookie)).data.attendance.some(a=>a.employeeId===emp.id));
console.log('PASS HTTP auth, own-data filtering, forbidden writes/payroll, CSRF, concurrent idempotency, actual short checkout, multiple same-day shifts, owner edit/credit repeat, split deduction, employee reflection, payroll 96000 KRW, retirement/session revocation/record retention');
