import { createRequire } from 'node:module';
import { writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const origin=process.env.TEST_ORIGIN||'http://localhost:3000';
assert(['localhost','127.0.0.1'].includes(new URL(origin).hostname),'Use a local demo server');
assert.equal((await (await fetch(origin+'/api/config')).json()).demo,true,'Use a demo server for browser verification');
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE});
const page=await browser.newPage({viewport:{width:1440,height:1000},locale:'ko-KR',timezoneId:'Asia/Seoul'});
process.on('unhandledRejection',async error=>{console.error(error);try{await page.screenshot({path:'docs/screenshots/failure.png'});console.error((await page.locator('body').innerText()).slice(0,5000));}finally{await browser.close();process.exitCode=1;}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const remoteFonts=[];page.on('request',request=>{if(/fonts\.(googleapis|gstatic)\.com/.test(request.url()))remoteFonts.push(request.url());});
const results=[];
async function shot(name){await page.mouse.move(0,0);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.getByRole('status').waitFor({state:'hidden',timeout:6000}).catch(()=>{});await page.screenshot({path:`docs/screenshots/${name}.png`,fullPage:false});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,name+' horizontal overflow');const small=await page.evaluate(()=>Array.from(document.querySelectorAll('button,summary')).map(e=>({label:e.textContent?.trim()||e.getAttribute('aria-label'),r:e.getBoundingClientRect()})).filter(x=>x.r.width>0&&x.r.height>0&&(x.r.width<43.9||x.r.height<43.9)).map(x=>({label:x.label,width:x.r.width,height:x.r.height})));assert.deepEqual(small,[],name+' undersized touch targets');const typography=await page.evaluate(()=>({body:parseFloat(getComputedStyle(document.body).fontSize),inputs:[...document.querySelectorAll('input,select,textarea')].filter(e=>e.getBoundingClientRect().width>0).map(e=>parseFloat(getComputedStyle(e).fontSize))}));assert(typography.body>=15,name+' body font');assert(typography.inputs.every(size=>size>=16),name+' input font');results.push({screen:name,noHorizontalOverflow:true,touchTargets44:true,typography});}
async function login(username,password='demo1234'){await page.getByLabel('아이디',{exact:true}).fill(username);await page.getByLabel('비밀번호',{exact:true}).fill(password);await page.getByRole('button',{name:'로그인',exact:true}).click();await page.getByRole('button',{name:'로그아웃',exact:true}).waitFor();}
async function nav(name,mobile=false){await page.locator(mobile?'.mobile-nav':'.sidebar nav').getByText(name,{exact:true}).click();}
await page.goto(origin);await page.getByRole('button',{name:'로그인',exact:true}).waitFor();await shot('login-desktop');await login('owner');await shot('owner-today-desktop');
for(const [name,file]of [['출석부','attendance'],['직원','employees'],['급여','payroll']]){await nav(name);await shot(`owner-${file}-desktop`);}
await page.setViewportSize({width:768,height:1024});await shot('owner-payroll-tablet');await nav('오늘');await shot('owner-today-tablet');await page.setViewportSize({width:1440,height:1000});await nav('출석부');await page.getByRole('button',{name:'기록 추가',exact:true}).click();await page.getByRole('dialog').waitFor();await shot('owner-record-input-desktop');await page.getByLabel('출근 · 한국 시각').fill('2025-01-02T10:00');await page.getByLabel('퇴근 · 미퇴근은 비워 두세요').fill('2025-01-02T09:00');await page.getByLabel('수정 사유').fill('오류 상태 검증');await page.getByRole('button',{name:'저장하기',exact:true}).click();await page.getByRole('dialog').getByRole('alert').waitFor();await shot('owner-record-error-desktop');await page.getByRole('button',{name:'닫기',exact:true}).click();
await page.setViewportSize({width:390,height:844});
for(const [name,file]of [['오늘','today'],['출석부','attendance'],['직원','employees'],['급여','payroll']]){await nav(name,true);await shot(`owner-${file}-mobile`);}
await page.setViewportSize({width:360,height:780});for(const [name,file]of [['오늘','today'],['출석부','attendance'],['직원','employees'],['급여','payroll']]){await nav(name,true);await shot(`owner-${file}-small-mobile`);}await page.setViewportSize({width:390,height:844});await nav('직원',true);await page.getByRole('button',{name:'직원 등록',exact:true}).click();await shot('owner-employee-input-mobile');await page.getByRole('button',{name:'닫기',exact:true}).click();for(const [label,file]of [['시급 이력','wage'],['산정기간','period']]){await page.getByRole('button',{name:label,exact:true}).first().click();await shot(`owner-${file}-input-mobile`);await page.getByRole('button',{name:'닫기',exact:true}).click();}
await nav('출석부',true);await page.getByRole('button',{name:'기록 추가',exact:true}).click();await shot('owner-record-input-mobile');await page.getByRole('button',{name:'닫기',exact:true}).click();await page.getByLabel('근무일',{exact:true}).fill('2000-01-01');await shot('owner-attendance-empty-mobile');
await page.getByRole('button',{name:'로그아웃',exact:true}).click();await page.getByRole('button',{name:'로그인',exact:true}).waitFor();await shot('login-mobile');await login('employee');
for(const [name,file]of [['오늘','today'],['내 출석부','attendance'],['내 정보','profile']]){await nav(name,true);await shot(`employee-${file}-mobile`);assert.equal(await page.getByText('예상 급여',{exact:false}).count(),0);}
await nav('내 정보',true);await page.getByRole('button',{name:'비밀번호 변경',exact:true}).click();await shot('employee-password-input-mobile');await page.getByRole('button',{name:'닫기',exact:true}).click();
await nav('내 출석부',true);await page.getByRole('button',{name:'조정 내역',exact:true}).click();await shot('employee-audit-mobile');await page.getByRole('button',{name:'닫기',exact:true}).click();
await page.setViewportSize({width:1440,height:1000});for(const [name,file]of [['오늘','today'],['내 출석부','attendance'],['내 정보','profile']]){await nav(name);await shot(`employee-${file}-desktop`);}
await page.setViewportSize({width:360,height:780});for(const [name,file]of [['오늘','today'],['내 출석부','attendance'],['내 정보','profile']]){await nav(name,true);await shot(`employee-${file}-small-mobile`);}

// Complete a fresh employee's mobile lifecycle through the actual UI.
await page.getByRole('button',{name:'로그아웃',exact:true}).click();await page.getByRole('button',{name:'로그인',exact:true}).waitFor();await login('owner');await nav('직원',true);
const flowName='화면검증 '+Date.now(),flowUsername='ui'+Date.now();
await page.getByRole('button',{name:'직원 등록',exact:true}).click();
await page.getByLabel('직원 이름',{exact:true}).fill(flowName);await page.getByLabel('입사일',{exact:true}).fill('2026-01-01');await page.getByLabel('로그인 아이디',{exact:true}).fill(flowUsername);await page.getByLabel('임시 비밀번호 (8자 이상)',{exact:true}).fill('testpass123');await page.getByRole('button',{name:'저장하기',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
await page.locator('article').filter({hasText:flowName}).getByRole('button',{name:'시급 이력',exact:true}).click();await page.getByLabel('새 시급 (원)',{exact:true}).fill('12000');await page.getByLabel('적용 시작일',{exact:true}).fill('2026-01-01');await page.getByRole('button',{name:'저장하기',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
await page.getByRole('button',{name:'로그아웃',exact:true}).click();await page.getByRole('button',{name:'로그인',exact:true}).waitFor();await login(flowUsername,'testpass123');
await page.route('**/api/clock',route=>route.abort(),{times:1});await page.getByRole('button',{name:'출근하기',exact:true}).click();await page.locator('.global-error').waitFor();await shot('employee-network-error-mobile');
await page.getByRole('button',{name:'요청 다시 시도',exact:true}).click();await page.getByRole('button',{name:'퇴근하기',exact:true}).waitFor();await page.getByRole('button',{name:'퇴근하기',exact:true}).click();await page.getByText('차감시간 확인 필요 · 급여 합계에서 제외',{exact:true}).waitFor();await shot('employee-short-checkout-mobile');
await page.getByRole('button',{name:'로그아웃',exact:true}).click();await page.getByRole('button',{name:'로그인',exact:true}).waitFor();await login('owner');await nav('출석부',true);await page.locator('.filters select').selectOption({label:flowName});await page.getByRole('button',{name:'기록 수정',exact:true}).click();
const yesterday=new Date(Date.now()+9*3600000-86400000).toISOString().slice(0,10);await page.getByLabel('출근 · 한국 시각',{exact:true}).fill(yesterday+'T10:00');await page.getByLabel('퇴근 · 미퇴근은 비워 두세요',{exact:true}).fill(yesterday+'T22:00');await page.getByLabel('수정 사유',{exact:true}).fill('화면 흐름 검증 · 실제 근무시간 보정');await page.getByRole('button',{name:'저장하기',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.route('**/api/state?*',route=>route.abort(),{times:1});await page.getByRole('button',{name:'근무 1시간 인정',exact:true}).click();await page.locator('.global-error').filter({hasText:'저장됐지만 최신 기록을 불러오지 못했습니다.'}).waitFor();await shot('owner-saved-refresh-error-mobile');await page.getByRole('button',{name:'다시 불러오기',exact:true}).click();await page.getByText('11시간 0분',{exact:true}).waitFor();await page.getByRole('button',{name:'확인',exact:true}).click();await page.getByText('확인 완료',{exact:true}).waitFor();await shot('owner-corrected-approved-mobile');
await page.getByRole('button',{name:'로그아웃',exact:true}).click();await page.getByRole('button',{name:'로그인',exact:true}).waitFor();await login(flowUsername,'testpass123');await nav('내 출석부',true);await page.getByText('11시간 0분',{exact:true}).waitFor();await page.getByText('확인 완료',{exact:true}).waitFor();await shot('employee-correction-reflected-mobile');results.push({flow:'owner creates account/wage → employee network failure/retry → clock in/out → owner corrects/credits/confirms → employee sees 11h confirmed',passed:true});
assert.deepEqual(errors,[]);assert.deepEqual(remoteFonts,[]);await writeFile('docs/screenshots/browser-results.json',JSON.stringify({results,pageErrors:errors,remoteFontRequests:remoteFonts},null,2));console.log(`PASS ${results.filter(r=>r.screen).length} desktop/mobile/input/error/empty screenshots + complete lifecycle, no horizontal overflow, no page errors`);await browser.close();
